### ISSUE TITLE
the blog is down

### ISSUE THREAD

**Issue by lpryszcz** [funoverip/verisure-alarm#1]
Hi Jerome, I'd love to use this repo however the blog send to be down. Do you have another copy or could you share some hints how to stay here? 

I'm interested in setting up a custom DNS server in my network in order to use the system without internet access.

**Comment by funoverip** [comment]
Hi, I know, it's a shame. It's on my todolist since too long now :)
Drop me an email at jerome.nokin@gmail.com and I will send you a PDF version of the Verisure articles.
Cheers.

**Comment by lpryszcz** [comment]
Actually, the web.archive.org has captured your blog all right :) thanks! 
https://web.archive.org/web/20200726092905/https://funoverip.net/
