### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by velzend** [funoverip/verisure-alarm#2]
Dear FunOverIP,

I really enjoyed reading all the information you provided. 

Are you still using your Verisure alarm system? 
Did you write part 3 and maybe more on the Verisure alarm?

I would like to control the Verisure alarm system locally, preferable over the network (REST and Websockets for events).

I am talking about the newer Verisure controller:
![image](https://github.com/funoverip/verisure-alarm/assets/5188551/dc5a03a4-cbfb-4def-aa2b-e75a69e0c8c1)

And remote key-pad:
![image](https://github.com/funoverip/verisure-alarm/assets/5188551/3a3b2a2e-6569-4d6a-95df-1c7a1d2cfd85)

Regards,

**Comment by funoverip** [comment]
Sorry Dennis, not really. This project is 9 years old :)
Part 3 has finally be transformed into business, as they become my first customer.

**Comment by velzend** [comment]
That's a nice opportunity to get into some serious business. Do you think it is feasible/ possible to hack the newest version of the Verisure components. I was looking in the Marketplace and found some second hand Verisure setups with expired subscription for a bargain (like 20€). What do you think?
